### ISSUE TITLE
Error in frontend 

### ISSUE THREAD

**Issue by GeluKu** [nigelpoulton/ckad#43]
Got this error in the frontend container

> djackets_vue@0.1.0 serve
> echo VUE_APP_API_URL=${API_URL} > .env && vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
<s> [webpack.Progress] 10% building 0/1 modules 1 active multi /app/node_modules/webpack-dev-server/client/index.js?http://10.244.0.15:8080&sockPath=/sockjs-node /app/node_modules/webpack/hot/dev-server.js ./src/main.js
<s> [webpack.Progress] 10% building 1/1 modules 0 active 
<s> [webpack.Progress] 10% building 1/1 modules 0 active 
<s> [webpack.Progress] 10% building 1/2 modules 1 active multi /app/node_modules/webpack/hot/dev-server.js /app/node_modules/webpack-dev-server/client/index.js?http://10.244.0.15:8080&sockPath=/sockjs-node ./src/main.js
<s> [webpack.Progress] 10% building 2/2 modules 0 active 
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
<s> [webpack.Progress] 10% building 2/3 modules 1 active /app/node_modules/cache-loader/dist/cjs.js??ref--12-0!/app/node_modules/babel-loader/lib/index.js!/app/src/main.js
<s> [webpack.Progress] 10% building 2/4 modules 2 active /app/node_modules/webpack-dev-server/client/index.js?http://10.244.0.15:8080&sockPath=/sockjs-node
<s> [webpack.Progress] 10% building 2/5 modules 3 active /app/node_modules/webpack/hot/dev-server.js
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by GeluKu** [comment]
Solved with the solution from issue #40
